[tool.isort]
line_length = 120
profile = "black"

[tool.black]
line-length = 120
target-version = ['py310']

[tool.mypy]
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true
disallow_untyped_defs = true

# Ignore specific packages
[[tool.mypy.overrides]]
module = [
    "transformers.*",
    "accelerate.*",
    "librosa.*",
    "soundfile.*",
    "datasets.*",
    "jiwer.*",
    "scipy.*"
]
ignore_missing_imports = true
follow_imports = "skip"
