[tool.isort]
line_length = 120

[tool.black]
line-length = 120
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.mypy]
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

# Ignore specific packages
[[tool.mypy.overrides]]
module = [
    "transformers.*",
    "accelerate.*"
]
ignore_missing_imports = true
follow_imports = "skip"
