name: CI

on: [push]

jobs:
  build:
    runs-on:  ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r config/requirements_qa.txt

    - name: Check python init files
      run: |
        source config/bootstrap.sh
        python config/py_init_checker.py --directory .

    - name: Analyzing the code with pylint
      run: |
        source config/bootstrap.sh
        pylint . --rcfile config/.pylintrc

    - name: Analyzing the code with isort
      run: |
        source config/bootstrap.sh
        isort . -c

    - name: Analyzing the code with black
      run: |
        source config/bootstrap.sh
        black . --check

    - name: Analyzing the code with mypy
      run: |
        source config/bootstrap.sh
        mypy .
